### PR TITLE
Adding v1beta1

### PR DESCRIPTION
**Pull request by danielwhatmuff**
- Generated using `https://raw.githubusercontent.com/grafeas/grafeas/master/proto/v1beta1/swagger/grafeas.swagger.json`

### CODE REVIEW

**Comment by danielwhatmuff** [comment]
@googlebot I signed it!

**Comment by clrprod** [comment]
Looks reasonable to me - I don't know what the status of these client libraries are though.

**Comment by clrprod** [comment]
Thanks for sending these in though :D Have you tested this and is it working? My leaning is to just merge this and we can deal with it later.

**Comment by danielwhatmuff** [comment]
> Looks reasonable to me - I don't know what the status of these client libraries are though.

Me neither! I noticed there is no `swagger.yaml` in the latest grafeas release so

**Comment by danielwhatmuff** [comment]
Related - https://github.com/grafeas/grafeas/issues/95

**Comment by vtsao** [comment]
Last I checked, the protoc tool wasn't able to generate a correct Swagger spec from the protos because the OpenAPI spec isn't rich enough to support the HTTP mappings we use in the protos (https://cloud.google.com/apis/design/standard_methods). @aysylu on the status of this.

@danielwhatmuff are you using this Python client library for v1beta1? If you are, and you need it, I'm happy to merge this generated library works for you in its current state.

**Comment by danielwhatmuff** [comment]
I was trying to get it working yes but am getting 404s when making calls to the docker image `grafeas/grafeas:0.1.0` running locally.

**Comment by danielwhatmuff** [comment]
Is there an alternative image tag I should test against?

**Comment by clrprod** [comment]
I think we have a 0.1.1 version with a bug fixed, but I don't think it's
that bug.

**Comment by danielwhatmuff** [comment]
@vtsao @aysylu what are your thoughts on this?

**Comment by aysylu** [comment]
@danielwhatmuff: you'll want to use `v0.1.0` tag: `docker pull us.gcr.io/grafeas/grafeas-server:v0.1.0`. Does it work with this tag?

**Comment by aysylu** [comment]
@danielwhatmuff: we've moved to using semantic versioning for the server and client lib releases, see [versioning doc](https://github.com/grafeas/grafeas/blob/master/docs/versioning.md) and [client-go](https://github.com/grafeas/client-go). Could you please re-generate this to be `0.1.0` version? Thank you!

**Comment by danielwhatmuff** [comment]
Sure, I will try with the 0.1.0 version.

**Comment by aysylu** [comment]
@danielwhatmuff: thanks!

**Comment by aysylu** [comment]
Closing this due to no activity since Sep 2019. Happy to review another PR for the `0.1.0` version of the client.

**Pull request closed without merging**
